Layout/IndentationWidth:
  # Number of spaces for each indentation level.
  Width: 2
Style/NestedTernaryOperator:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 90
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Security/Open:
  Enabled: false

